rules:
  linebreak-style:
    - error
    - unix
  no-undef:
    - error
    - typeof: true
  no-mixed-spaces-and-tabs:
    - error
  no-console:
    - error
  no-unused-vars:
    - error
    - varsIgnorePattern: "^_"
      argsIgnorePattern: "^_"
  comma-dangle:
    - error
    - only-multiline
env:
  node: true
  es6: true
extends: 'eslint:recommended'
